[package]

name = "threadpool"
version = "0.2.1"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/frewsxcv/rust-threadpool"
homepage = "https://github.com/frewsxcv/rust-threadpool"
documentation = "https://frewsxcv.github.io/rust-threadpool"
description = """
A thread pool for running a number of jobs on a fixed set of worker threads.
"""

[[test]]
name = "criterion"
path = "tests/criterion.rs"

[features]
unstable = ["criterion", "criterion-macros"]

[dependencies]
#criterion = { git = "https://github.com/japaric/criterion.rs.git" }
criterion = { path = "../criterion.rs", optional=true }
criterion-macros = { path = "../criterion.rs/macros", optional=true }
